### ISSUE TITLE
Thoughts on 5etools native docker?

### ISSUE THREAD

**Issue by jshank** [Jafner/5etools-docker#7]
I noticed in the updates from 5etools they now have a native self-updating docker image. Any thoughts on integrating their approach or a difference between your image and theirs? I haven't found much documentation on theirs so sticking with yours for now.

https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/pkgs/container/5etools

**Comment by Jafner** [comment]
Theirs is very simple. Until 1.173.2 it was literally just `dragas/thttpd` and then copying the repo into the directory to be served.  
Today, it starts from alpine and installs lighttpd then copies the repo into the image.  

The biggest difference between my image and theirs is that my _image_ does not contain any 5eTools data. Theirs contains the full contents of each release. This has a couple pros and cons.  

1. `jafner/5etools-docker`  can be pulled without images. For my VPS with 25 GB of storage, this is a big deal. 5eTools is ~100 MB without images, and ~4.3 GB with images. 
2. (In theory) `jafner/5etools-docker` can update incrementally, rather than pulling an entire new image. This is not working properly right now. But this is a useful feature of a git-based approach. Instead of pulling a new 4.3 GB update to get from 1.172.0 to 1.172.2, you can just pull the kilobytes of actual changes.

The other factor is the owner/maintainer of each project.
1. `5etools-mirror-1/5etools` is from the creators of 5eTools. Maybe you trust them more than you trust me. Both projects are open, but I could put a bitcoin miner in an update at some point. I'm a nobody and they're the official project runners. 
2. On the other hand, I'm probably more likely to make changes to this repo to add or modify features in response to issues.

**Comment by Jafner** [comment]
I noticed that the official image pulled in about 16.5 minutes, while my image _updated_ from GITHUB-NOIMG to GITHUB in only 4 minutes. I wonder if GHCR has a lower bandwidth limit than Github Git.

**Comment by jshank** [comment]
Awesome, thanks for the comments and insight @Jafner. The flexibility of your approach and supported environment variables make your solution better for me as well.
